apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicpulse

resources:
  - ../../base
  - pdb.yaml

images:
  - name: ghcr.io/PLACEHOLDER/civicpulse-backend
    newName: ghcr.io/${GHCR_NAMESPACE}/civicpulse-backend
    newTag: ${IMAGE_TAG}
  - name: ghcr.io/PLACEHOLDER/civicpulse-frontend
    newName: ghcr.io/${GHCR_NAMESPACE}/civicpulse-frontend
    newTag: ${IMAGE_TAG}