apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicpulse

resources:
  - ../../base

images:
  - name: ghcr.io/PLACEHOLDER/civicpulse-backend
    newName: civicpulse-backend
    newTag: dev
  - name: ghcr.io/PLACEHOLDER/civicpulse-frontend
    newName: civicpulse-frontend
    newTag: dev

patches:
  - path: replica-patch.yaml